apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sglang.fullname" . }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sglang.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sglang.labels" . | nindent 8 }}
    spec:
      runtimeClassName: nvidia
      containers:
      - name: sglang
        image: lmsysorg/sglang:latest
        command: [ "python3", "-m", "sglang.launch_server" ]
        args:
        - "--model-path"
        - "Qwen/Qwen3-4B-Instruct-2507"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "30000"
        ports:
        - containerPort: 30000
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 8
            memory: 40Gi
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: model-storage
        livenessProbe:
          httpGet:
            path: /health
            port: 30000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health_generate
            port: 30000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: {{ include "sglang.fullame" . }}
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
