apiVersion: v1
kind: Service
metadata:
  name: {{ include "sglang.fullname" . }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sglang.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 30000
  type: LoadBalancer
